### ISSUE TITLE
Questions about the objectives of the training

### ISSUE THREAD

**Issue by famuvie** [VABAR/vibass_dev_introductory_training#1]
Reading the [objectives of the training](https://github.com/VABAR/vibass_dev_introductory_training#readme) and with the course materials at hand, do you think that:

1. the __goal of the training__ completely and accurately covers what we want the participant to achieve with the training?

2. the __operational goals__ described above are necessary and sufficient to achieve the goal of the training?

3. what we __actually do__ in the course is necessary and sufficient to achieve the operational goals?

**Comment by DavidConesa** [comment]
Q1: my opinion is that the goal of the training as it is written could be a little bit ambitious. I have been teaching this kind of courses for some time (a 10-12 hours course I mean) and I always have the feeling that attendants get an idea of the Bayesian ideas, so I think that the sentence:
"At the end of the course, participants will be able to start using Bayesian statistics in their field, having acquired the foundations needed to learn and understand more specific methods and models"
provides the idea of START using and ADQUIRED the FOUNDATIONS which I think make a clear statement of the goal.
So, yes, I think the goal completely and accurately covers what we want the participant to achieve with the training.

Q2: With respect to the operational goals I would change a little bit the third one to try to include the idea that random samples are extracted from the posterior distribution of the unknown.
3. Summarise inferences and predictions using posterior distributions and prior/posterior predictive distributions either using them or random samples extracted from them.
Apart from this, the remaining ones seem fine to me.
Anyway, my impression is that (taking into account that we only have 12 hours) maybe the list is too ambitious. INLA, BayesX, maybe too much to be incorporated in here. I know that we only mention them and use them just to show that people can go home and do things (which I think it is the idea). But still have the feeling that other simple packages would provide the same feeling. For me, it depends a lot on the topic that attendees would get the other two days of training. This year with INLA, there was no need for it, but, when no INLA is around, it could be fine. But INLA is not easy to tell in an hour lectures (or maybe it is).
We should discuss this further.

Q3: This is the important question to me. What we do is necessary and sufficient? I think so, there is always room for improvement, but we have been preparing a good material and we have been teaching it properly.

**Comment by AnabelUV** [comment]
1. About the goal of the training, I think it should a bit too ambitious... if they are able to to use Bayesian Statistics completely with a 2 day course, which is the point of giving larger courses in the university. I would say "participants would be able to think in the implementation of Bayesian statistics in their field"

2. Regarding the operational goals maybe 9 and 8 are too much for a 12 hours course. I would like them to know the insights of the methods but no to apply them or to completely understand them. 

3. what we actually do in the course is necessary and sufficient to achieve the operational goals?
For this question, if we mean if the material is enough? I think yes, it is... however I don't think we have the time to achieve perfectly all of them and the learning process depends a great deal in what we are able to involve them in the class. 

EXTRA. Last but no least, regarding Pre-requisites, I do not like much how it is written... Yo say that they do not need to know Bayesian statistics and I agree... but what about maths and/or statistics? The language we use is quite Technical sometimes (parameters, distribution and so on) So, instead of telling them what they do not need to know, I would talk about what the actually need. 

"People with some knowledge about probability and statistics (a basic first course would suffice). In particular the most used concepts are probability distributions and parameters. It is also important to have some knowledge  about population and samples"

**Comment by MarkJBrewer** [comment]
I think the overall structure is sound, we have a good amount of theory, but with a lot of practical activity well-mixed in the timetable to provide inspiration. I like that Day 2 gets people coding the algorithms "by hand" - and then switches to a couple of command-line options in packages - it's mostly about showcasing the opportunities and helping point people in the right direction.

The operational goals are all "technical", in a sense - could we include something about understanding the place of Bayesian modelling in the general wider landscape of data analysis - e.g. should we enable them to understand when a Bayesian analysis would be a good idea, or better than alternatives (or not!) and a broad idea of why...? That isn't the same as being an expert, of course.

For me such a course is all about understanding the possibilities, and getting idea of where to go next, what aspects you need to study further to be able to become a competent Bayesian in your field.

Sorry for the delay in responding, but 3 hours ago we finally submitted our bid for our next 5 years of government funding...

**Comment by becarioprecario** [comment]
I agree with all the previous comments. Some other ideas that I wanted to share are below.

Q1: One of the goals of the training should also be to understand a Bayesian analysis in practice. In particular, the course participants should be able to identify the model, priors, etc. as presented in research papers (at least for GLM and some GLMMs). This implies identifying the problem, the model required and whether the likelihood and priors are reasonable. Although not stated dung the course, I believe that this is (or should be) a by-product of attending the course.

Q2: The operational goals are adequate, I think. I would add that they should be able to understand a Bayesian analysis presented in a research paper.

Q·: I think that course attendants would benefit from more hands-on exercises and computer labs could be given more time. One of the theory slots (about very general modeling issues) might be reduced or dropped completely.

**Comment by armero79** [comment]
Q1. I think the objective of the course is well defined although it may be a bit ambitious. I would possibly specify it a bit more by saying:
At the end of the course, participants will be able to start using Bayesian statistics in simple models in their field and to have acquired the necessary foundations to learn and understand more specific methods and models. 
Now the Pre-requisites. I agre with Anabel and I think that we need to be a bit more specific. I would propose 
People with some knowledge about probability, statistics (a basic course would be sufficient) and R.
I do not include knowledge about population and samples in the proposal because I understand that our targed populations are always probability distributions and I think it is better not to open the subject. 

Q2. With regard to the proposed operational goals: 
-	1 and 2 ok. In goal 2, would it be more appropriate to introduce normal data than continuous data?
-	I would introduce a new goal:  Extract practical information from analytical posterior distributions.
-	And I would  propose a new  goal based on current 3 and 4th goals: Summarise inferences and predictions of quantities of interest and derived functions using random samples from relevant probability distributions.
-	I would propose a new goal triying to incorporate Mark’s comments: Understand the conceptual and output differences between Bayesian and frequentist analyses, especially in estimation, prediction and hypothesis testing.
-	I would combine the current points 5 and 6 into one.
-	I don't remember if we worked with Gibbs. If yes, then it should appear at some point, I would imagine in the current 7.
-  In goal 10, I will delete …like INLA or BayesX …in order to be more general. 

Q3. I would say yes. If I think about the subject we explained on the first day (which is the one I know best) I think we could put a bit more emphasis on the difference between Bayesian and frequentist methods. I also think we could introduce hypothesis testing in a simple and above all conceptual way. To work with the Bayes factor in the case of point contrasts in the continuous world may be excessive, but to pose the problem could possibly be conceptually interesting. We talked about it

**Comment by famuvie** [comment]
Thank you for your input.

I've synthesised your responses in a [slides presentation](http://vabar.es/vibass_dev_introductory_training/dev_intro_training.html) that we reviewed together on a meeting at 2021-12-17.

Here is a [summary of the conclusions of the meeting](https://github.com/VABAR/vibass_dev_introductory_training/blob/main/20211227_minutes.md), which I used to update the Objective of the training course and the Operational Goals displayed in [Readme.md](https://github.com/VABAR/vibass_dev_introductory_training/blob/main/README.md).
